import {
  Brain,
  Cpu,
  Code,
  Shield,
  Database,
  Cloud,
  Palette,
  Award,
  Building,
  BookOpen,
  Map,
  TrendingUp,
  Briefcase,
  ExternalLink,
  ChevronRight,
  Search,
  Filter,
  CheckCircle,
  HelpCircle,
  Clock,
  Lock,
  Calendar,
  AlertTriangle,
  Play
} from 'lucide-react';

export const CAREER_ICONS = {
  ai: Brain,
  dev: Code,
  data: Database,
  security: Shield,
  cloud: Cloud,
  design: Palette,
  certification: Award,
  company: Building,
  resource: BookOpen,
  roadmap: Map,
  salary: TrendingUp,
  career: Briefcase,
  external: ExternalLink,
  chevron: ChevronRight,
  search: Search,
  filter: Filter,
  check: CheckCircle,
  help: HelpCircle,
  clock: Clock,
  lock: Lock,
  calendar: Calendar,
  warning: AlertTriangle,
  play: Play
};
